# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

resources:
- repo: self

variables:
  kubernetesServiceConnection: Minikube

stages:
- stage: Deploy
  displayName: Deploy to minikube
  jobs:
  - job: Deploy
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: "KubernetesManifest@0"
      displayName: "Deploy"
      inputs:
        kubernetesServiceConnection: $(kubernetesServiceConnection)
        namespace: "default"
        #manifests: "manifests/*"
        containers: 'mandla21/api:pipeline'