# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: 'mandla21/api:pipeline'
  imageName: '$(username)/api:pipeline'

stages:
- stage: Build
  displayName: Build api image 
  jobs:  
  - job: Build
    displayName: Build 
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: echo "$(username)"
    - script: echo "$(password)"
      