# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: 'mandla21/api:pipeline'
  imageName: '$(username)/api:pipeline'

stages:
- stage: Build
  displayName: Build api image 
  jobs:  
  - job: Build
    displayName: Build 
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: Docker@2
        displayName: Building an image
        inputs:
          #command: build
          #dockerfile: '$(Build.SourcesDirectory)/API/API/dockerfile'
          containerRegistry: $(serviceConnection)
          tags: |
            $(tag)
      - script: docker login -u $(username) -p $(password)
        displayName: 'docker login'
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))

      - task: PublishPipelineArtifact@0
        inputs:
          artifactName: 'manifests'
          targetPath: 'manifests'
      - script: docker push $(imageName)
        displayName: 'docker push latest if this is the master branch'
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
      